### ISSUE TITLE
Issue generating graphs

### ISSUE THREAD

**Issue by adamotonete** [DeathBorn/mongo_ftdc_draw#1]
Hi, Using an already decoded ftdc file I'm receiving this error:

Traceback (most recent call last):
  File "/home/adamo/.local/bin/mongo_ftdc_draw", line 11, in <module>
    load_entry_point('mongo-ftdc-draw==0.1.0', 'console_scripts', 'mongo_ftdc_draw')()
  File "build/bdist.linux-x86_64/egg/mongo_ftdc_draw/mongo_ftdc_draw.py", line 155, in ftdc_main
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1137, in resource_filename
    self, resource_name
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1646, in get_resource_filename
    return self._extract_resource(manager, zip_path)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1667, in _extract_resource
    timestamp, size = self._get_date_and_size(self.zipinfo[zip_path])
KeyError: 'mongo_ftdc_draw/schemes/main.json'

**Comment by DeathBorn** [comment]
@adamobr could you tell how you run it?

I usually use this tool like this
```
ftdc decode diag_data/* --start='Fri Jul 6 8:00:00 EET 2018' --end='Fri Jul 6 20:00:00 EET 2018' --out="ftdc.json"

mongo_ftdc_draw -f=ftdc.json -o=ftdc.1.png -d '{"A":"2018-07-06 11:54:29","B":"2018-07-06 17:27:19"}'

```

it might be that there is missing key

**Comment by DeathBorn** [comment]
Ah. It seems I have newer version of it. I will update the code soon.
